# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b509f9c27c143e7cc1dc5a7b2c4500a9dbf731837dfb2542587a2eba89335b2b17d0f6054e02cda26c5562454fda27108ea0f387f067420962dbddcc36e9b249

test:
  secret_key_base: 918bc482e7bb6a05d1f9337002780f6f734645d3a088c0b3f451695b58a3f21ccbf8a1e9275d216a8009b8214407964198e345af973f782aaeed208ba0042708

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
